version: '3.9'

services:

# ---------------- PostgreSQL ----------------

  postgres:
    image: postgres:16

    container_name: ecommerce-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ecommerce

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

# ---------------- Redis ----------------

  redis:
    image: redis:latest

    container_name: ecommerce-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

# ---------------- RabbitMQ ----------------

  rabbitmq:
    image: rabbitmq:3-management

    container_name: ecommerce-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: unless-stopped

# ---------------- User Service ----------------

  userservice:

    build:
      context: .
      dockerfile: UserService.Api/Dockerfile

    container_name: userservice

    depends_on:
      - postgres

    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080

    ports:
      - "7001:8080"

    restart: unless-stopped

# ---------------- Product Service ----------------

  productservice:

    build:
      context: .
      dockerfile: ProductService.Api/Dockerfile

    container_name: productservice

    depends_on:
      - postgres
      - redis

    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080

    ports:
      - "7002:8080"

    restart: unless-stopped

# ---------------- Order Service ----------------

  orderservice:

    build:
      context: .
      dockerfile: OrderService.Api/Dockerfile

    container_name: orderservice

    depends_on:
      - postgres
      - rabbitmq
      - productservice

    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080

    ports:
      - "7003:8080"

    restart: unless-stopped

# ---------------- Worker ----------------

  worker:

    build:
      context: .
      dockerfile: OrderProcessor.Worker/Dockerfile

    container_name: order-worker

    depends_on:
      - rabbitmq
      - postgres

    environment:
      DOTNET_ENVIRONMENT: Docker

    restart: unless-stopped

# ---------------- Gateway ----------------

  gateway:

    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

    container_name: gateway

    depends_on:
      - userservice
      - productservice
      - orderservice

    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080

    ports:
      - "7000:8080"

    restart: unless-stopped

volumes:

  postgres-data: