name: .NET CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ECommerce.Microservices.sln

      - name: Build Solution
        run: dotnet build ECommerce.Microservices.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test ECommerce.Microservices.sln --no-build --configuration Release